version: '3.7'

services:
  b25:
    image: 68fpjc/b25
    ports:
      - 40773:40773
    environment:
      TZ: Asia/Tokyo
    depends_on:
      - bcas
    restart: unless-stopped

  bcas:
    image: 68fpjc/bcas
    privileged: true
    ports:
      - 40774:40774
    environment:
      TZ: Asia/Tokyo
    restart: unless-stopped
